apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATA_REDIS_PASSWORD: "6754011"
  JWT_SECRET: "{cipher}63ca8b3e32847b897b5ac3bbfd869e0e198bde9f183b3ff3a89e97324461022e"
  APIKEY_KIS_SECRET: "WsSeZqNgJiYJEYn2zxS/tu1uh5rhf+4k75EDcrEGdbaEdYLCy/yjt2NZQ9+8JX/pepdh6yEoPT67Dzku/nYM2b+wnzD9cNmj/x2tJCcnsEl7sU8WEOPne2idVNrqzkw3F/JpTRXar0pFwSbsHaQJPxs2cG8xfJWGC0+teu/7iWlxPPgS6dc="